import React, { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';

export default function Detail() {
    const router = useRouter();
    const {name} = router.query
    const {warna} = router.query
    return (
        <div className={styles.container}>
            <Head>
                <title>Generate Link</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Detail Barang</h1>
                <p className={styles.description}>
                Nama Barang: {name}
                <br/>
                Warna: {warna}
                </p>
            </main>
        </div>
    )
}
